# Form implementation generated from reading ui file '/Users/kami/2A/P2I.3/src/mon_appli.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Diag(object):
    def setupUi(self, Diag):
        Diag.setObjectName("Diag")
        Diag.resize(666, 694)
        self.pushButton = QtWidgets.QPushButton(parent=Diag)
        self.pushButton.setGeometry(QtCore.QRect(50, 20, 100, 32))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Diag)
        self.graphicsView.setGeometry(QtCore.QRect(20, 60, 171, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(parent=Diag)
        self.label.setGeometry(QtCore.QRect(270, 130, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Diag)
        QtCore.QMetaObject.connectSlotsByName(Diag)

    def retranslateUi(self, Diag):
        _translate = QtCore.QCoreApplication.translate
        Diag.setWindowTitle(_translate("Diag", "Dialog"))
        self.pushButton.setText(_translate("Diag", "importer"))
        self.label.setText(_translate("Diag", "Prédiction"))
